####################################################################################################################
# Configuration file for translations and locales                                                                  #
####################################################################################################################

parameters:    
    # array of available interface translations
    interface_translation_locales:
        en:
            code: en
            flag: gb.png
        it:
            code: it
            flag: it.png
        es:
            code: es
            flag: es.png
        
    # parameter to be used in routes.yml
    # add |[locale] if a new interface locale is available
    route_locale_requirements: '^es|en|cn$'

    simple_array_locales: [es, en, cn]
    
twig:
    globals:
        # parameter accessible from twig templates
        interface_translation_locales: "%interface_translation_locales%"