services:
    pattern:  /services
    defaults: {  page: 'services'} 
    
intermediation-sale:
    pattern:  /service/sale
    defaults: {  page: 'sale'}
    
intermediation-rent:
    pattern:  /service/rent
    defaults: {  page: 'rent'}
    
intermediation-financing:
    pattern:  /service/financial
    defaults: { page: 'financial' }
    
intermediation-supplies:
    pattern:  /service/supplies
    defaults: {  page: 'supplies'}
    
intermediation-insurance:
    pattern:  /service/insurance
    defaults: {  page: 'insurance'}

construction-interior:
    pattern:  /service/interior  
    defaults: {  page: 'interior'}
    
construction-safety-coordinator:
    pattern:  /service/safety-coordinator
    defaults: {  page: 'safety-coordinator'}
    
construction-construction:
    pattern:  /service/construction
    defaults: {  page: 'construction'}

certificates-certificates:
    pattern:  /service/certificates
    defaults: {  page: 'certificates'}
    
certificates-ite:
    pattern:  /service/ite
    defaults: {  page: 'ite'}
    
certificates-licenses:
    pattern:  /service/licenses
    defaults: {  page: 'licenses'}

complement-painting:
    pattern:  /service/painting
    defaults: {  page: 'painting'}
   
complement-cleaning:
    pattern:  /service/cleaning
    defaults: {  page: 'cleaning'}

templo-work-with-us:
    pattern:  /work-with-us
    defaults: {  page: 'work-with-us'}

templo-information:
    pattern:  /information
    defaults: {  page: 'information'}
    
templo-our-values:
    pattern:  /our-values
    defaults: {  page: 'our-values'}
    
templo-contact-us:
    pattern:  /contact-us
    defaults: {  page: 'contact-us'}
    
templo-find:
    pattern:  /find
    defaults: {  page: 'search-for'}
    
templo-ask:
    pattern:  /ask
    defaults: {  page: 'ask'}
    
templo-perfil:
    pattern:  /perfil-login
    defaults: {  page: 'perfil-login'}
    
